<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Makenzie Kerneckel">
<meta name="dcterms.date" content="2024-07-24">

<title>Makenzie Kerneckel - Partisan Politics and Violent Realities: Exploring the Impact of PAN Electoral Victories on Municipal Homicide Rates in Mexico</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Makenzie Kerneckel</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#i.-introduction" id="toc-i.-introduction" class="nav-link active" data-scroll-target="#i.-introduction">I. Introduction</a></li>
  <li><a href="#ii.-literature-review" id="toc-ii.-literature-review" class="nav-link" data-scroll-target="#ii.-literature-review">II. Literature Review</a></li>
  <li><a href="#iii.-data" id="toc-iii.-data" class="nav-link" data-scroll-target="#iii.-data">III. Data</a></li>
  <li><a href="#iv.-hypotheses" id="toc-iv.-hypotheses" class="nav-link" data-scroll-target="#iv.-hypotheses">IV. Hypotheses</a>
  <ul class="collapse">
  <li><a href="#extension-hypotheses" id="toc-extension-hypotheses" class="nav-link" data-scroll-target="#extension-hypotheses">Extension Hypotheses</a></li>
  </ul></li>
  <li><a href="#v.-research-design" id="toc-v.-research-design" class="nav-link" data-scroll-target="#v.-research-design">V. Research Design</a>
  <ul class="collapse">
  <li><a href="#extension-hypotheses-regression-models" id="toc-extension-hypotheses-regression-models" class="nav-link" data-scroll-target="#extension-hypotheses-regression-models">Extension Hypotheses Regression Models</a></li>
  </ul></li>
  <li><a href="#vi.-findings" id="toc-vi.-findings" class="nav-link" data-scroll-target="#vi.-findings">VI. Findings</a>
  <ul class="collapse">
  <li><a href="#graphical-analysis-of-violence-pattern" id="toc-graphical-analysis-of-violence-pattern" class="nav-link" data-scroll-target="#graphical-analysis-of-violence-pattern">Graphical Analysis of Violence Pattern</a></li>
  <li><a href="#regression-analysis" id="toc-regression-analysis" class="nav-link" data-scroll-target="#regression-analysis">Regression Analysis</a></li>
  </ul></li>
  <li><a href="#vii.-discussion-and-policy-implications" id="toc-vii.-discussion-and-policy-implications" class="nav-link" data-scroll-target="#vii.-discussion-and-policy-implications">VII. Discussion and Policy Implications</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Partisan Politics and Violent Realities: Exploring the Impact of PAN Electoral Victories on Municipal Homicide Rates in Mexico</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Makenzie Kerneckel </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Pennsylvania
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 24, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="i.-introduction" class="level1">
<h1>I. Introduction</h1>
<p>Turf wars for the control of drug trafficking corridors in Mexico have been associated with a lethal crisis of criminal violence in the country since the 1990s. After peaceful coexistence in the 1980s, six turf wars broke out between Mexico’s five major cartels (Tijuana, Juárez, Sinaloa, Gulf, and La Familia Michoacana) on the Pacific Coast between 1990 and 2006 <span class="citation" data-cites="trejo2018did">(<a href="#ref-trejo2018did" role="doc-biblioref">Trejo and Ley 2018</a>)</span>. Annual turf war deaths reached 1,400 in 2006 <span class="citation" data-cites="trejo2018did">(<a href="#ref-trejo2018did" role="doc-biblioref">Trejo and Ley 2018</a>)</span>. In 2006, the Felipe Calderón administration began the first large-scale deployment of federal troops against the drug cartels, marking the beginning of the “Mexican War on Drugs” <span class="citation" data-cites="espinosa2015did">(<a href="#ref-espinosa2015did" role="doc-biblioref">Espinosa and Rubin 2015</a>)</span>. To implement large-scale efforts to combat drug trafficking, the Calderón administration worked with PAN mayors and municipal police. The crackdowns on drug cartels under Calderón ushered in a dramatic spiral of violence <span class="citation" data-cites="trejo2018did">(<a href="#ref-trejo2018did" role="doc-biblioref">Trejo and Ley 2018</a>)</span>. Between 2007 and 2012, more than 70,000 people were murdered in intercartel conflicts <span class="citation" data-cites="trejo2018did">(<a href="#ref-trejo2018did" role="doc-biblioref">Trejo and Ley 2018</a>)</span>. For political context, Calderón was Mexico’s second National Action Party (PAN) president, continuing PAN’s control of the office after Vicente Fox’s electoral victory for PAN in 2000. Fox’s election as president represented the first opposition candidate to win the presidency of Mexico in recent history, ending the Institutional Revolutionary Party’s (PRI) hegemonic, 71-year-long rule <span class="citation" data-cites="trejo2018did">(<a href="#ref-trejo2018did" role="doc-biblioref">Trejo and Ley 2018</a>)</span>. The Institutional Revolutionary Party (PRI) has historically represented a center-right platform with a broad base of support, while the National Action Party (PAN) emerged as a conservative opposition advocating for free-market economics and social conservatism <span class="citation" data-cites="cfr2024">(<a href="#ref-cfr2024" role="doc-biblioref">Foreign Relations 2024</a>)</span>. Afrter Calderón, President Enrique Peña Nieto (PRI) initiated reform efforts in 2012, which, although initially yielding decreases in homicides, ultimately fell short in tackling deep-rooted corruption and crime-related violence, culminating in a peak of 33,341 homicides in 2018 <span class="citation" data-cites="cfr2024">(<a href="#ref-cfr2024" role="doc-biblioref">Foreign Relations 2024</a>)</span>. In response to widespread criticism of militarized approaches, President Andrés Manuel López Obrador, a left-wing candidate of the MORENA party, upon assuming office in 2018, vowed to shift towards civilian-led policing; however, despite the implementation of initiatives like the creation of a new National Guard, violence levels have persistently remained high, amplifying the challenges in governance, security, and anti-cartel endeavors <span class="citation" data-cites="cfr2024">(<a href="#ref-cfr2024" role="doc-biblioref">Foreign Relations 2024</a>)</span>.</p>
<p>This study delves into the relationship between the success of PAN candidates in Mexican municipal elections and the post-election municipal homicide rate per 100,000 people, while also considering the impact of party rotation in mayoral office and the stability of PAN mayoral governance. Inspired by the work of Trejo and Ley (2018), this research challenges the traditional understanding of a clear separation between government authorities and organized crime groups (OCGs), aiming to explore the ‘gray zone’ where these entities intersect through informal protection systems <span class="citation" data-cites="trejo2018did">(<a href="#ref-trejo2018did" role="doc-biblioref">Trejo and Ley 2018</a>)</span>. Understanding how PAN governance and party alternation may disrupt state-criminal arrangements is essential for comprehending the broader dynamics of violence and governance in Mexico. Independent variables include the margin of victory for the PAN candidate, a municipal alternation index measuring party rotation, and a PAN power index assessing the stability of PAN mayoral terms. The dependent variable is the post-election municipal homicide rate per 100,000 people, encompassing all homicides, not solely those associated with intercartel conflicts.</p>
<p>Mayors play a crucial role in this context. They appoint municipal police chiefs and establish policies governing police conduct <span class="citation" data-cites="dell2015trafficking">(<a href="#ref-dell2015trafficking" role="doc-biblioref">Dell 2015</a>)</span>. Consequently, PAN mayors could potentially bolster Calderón’s, and other PAN presidents’, anti-drug efforts by appointing law enforcement authorities amenable to cooperation and by encouraging information-sharing with the PAN federal government. Qualitative evidence suggests that under Calderón’s administration, PAN mayors were more inclined to seek law enforcement assistance from the PAN federal government compared to their non-PAN counterparts <span class="citation" data-cites="dell2015trafficking">(<a href="#ref-dell2015trafficking" role="doc-biblioref">Dell 2015</a>)</span>. The propensity for PAN mayors to support Calderón’s war on drugs may stem from various factors, including enhanced cooperation among authorities from the same party, disparities in corruption levels, or ideological alignment <span class="citation" data-cites="dell2015trafficking">(<a href="#ref-dell2015trafficking" role="doc-biblioref">Dell 2015</a>)</span>. Ultimately, mayors matter for homicide rates at the municipal level because PAN drug-war operations involving the intervention of federal police and military in cartel activity are most effective when local authorities are politically aligned with the federal government.</p>
</section>
<section id="ii.-literature-review" class="level1">
<h1>II. Literature Review</h1>
<p>Previously, scholars have focused on identifying why intercartel violence in Mexico broke out in the early 2000s and estimating the causal effects of military interventions under Calderón on homicide rates in Mexico. According to a 2018 paper by Guillermo Trejo and Sandra Ley, the rotation of political parties in state gubernatorial power in Mexico between 1991 and 2006 significantly contributed to the outbreak of intercartel violence and large-scale criminal wars <span class="citation" data-cites="trejo2018did">(<a href="#ref-trejo2018did" role="doc-biblioref">Trejo and Ley 2018</a>)</span>. Their paper focused on analyzing the period from 1991 to 2006, prior to Calderón’s federal intervention. Trejo and Ley highlight the role of top and mid-level officials’ removal from key state-level institutions, such as the state attorney’s office and the state judicial police, in disrupting informal protections for drug cartels previously provided under the one-party rule of the PRI. From its founding in 1929 to 1988, PRI had won every gubernatorial election in Mexico’s 31 states and nearly all municipal races <span class="citation" data-cites="trejo2018did">(<a href="#ref-trejo2018did" role="doc-biblioref">Trejo and Ley 2018</a>)</span>. The study’s key finding reveals a 55.3% increase in violence in municipalities from states experiencing party alternation at the governor level compared to those under PRI hegemony, indicating a loss of cartel protection <span class="citation" data-cites="trejo2018did">(<a href="#ref-trejo2018did" role="doc-biblioref">Trejo and Ley 2018</a>)</span>. Economic factors and organizational dynamics further strengthened this relationship. Further, time trend analysis suggests a surge in violence during the initial year of opposition governors, reflecting a disruption in government protection networks. Ultimately, Trejo and Ley’s “instability hypothesis” argues that when PRI lost power at the state level an informal network of cartel protection was thrown off leading to an outbreak of inter-cartel violence. Contrary to Trejo and Ley, Melissa Dell’s 2015 paper “Trafficking Networks and the Mexican Drug War” concentrates on the surge in violence following the Mexican government’s War on Drugs between 2007 and 2012, attributing the escalation to rival traffickers vying for territories after crackdowns initiated by PAN mayors, which diverted drug traffic and intensified violence along alternative routes <span class="citation" data-cites="dell2015trafficking">(<a href="#ref-dell2015trafficking" role="doc-biblioref">Dell 2015</a>)</span>. Dell’s “diversion hypothesis” posits that crackdowns in one area (i.e.&nbsp;PAN municipalities) lead to the diversion of drug activity and homicides to other regions without substantial reduction <span class="citation" data-cites="dell2015trafficking">(<a href="#ref-dell2015trafficking" role="doc-biblioref">Dell 2015</a>)</span>. The key finding indicates that close PAN victories at the municipal level led to approximately 33 more drug trade-related homicides per 100,000 people annually during a mayor’s three-year term <span class="citation" data-cites="dell2015trafficking">(<a href="#ref-dell2015trafficking" role="doc-biblioref">Dell 2015</a>)</span>.</p>
<p>While prior research has provided valuable insights into the drivers of drug-related violence in Mexico, there remains a gap in understanding how political governance factors, particularly related to PAN governance stability and mayoral turnover, influence homicide rates at the municipal level after the war on drugs began in 2006 extending to 2020. There are two specific gaps that this paper seeks to address. First, earlier contributions, like Dell, have focused exclusively on drug-related homicides which are defined as “any instance in which a civilian kills another civilian, with at least one of the parties involved in the drug trade” <span class="citation" data-cites="dell2015trafficking">(<a href="#ref-dell2015trafficking" role="doc-biblioref">Dell 2015</a>)</span>. This paper uses general homicide rates to include deaths beyond the drug-related homicide definition. For example, instances of those killed in armed clashes between police and organized criminals and the deaths of undocumented immigrants who were targeted by drug cartels for profit during the war on drugs <span class="citation" data-cites="rosa2022mexican">(<a href="#ref-rosa2022mexican" role="doc-biblioref">Rosa Rodrı́guez 2022</a>)</span>. This paper sees overall homicide rates as a better measure of the intensity of violence that emerged following the declaration of the Mexican War on Drugs. Second, while Trejo and Ley focus on the impact of party alternation in gubernatorial power on violence between cartels, this paper focuses on the impact of party alternation in mayoral power on municipal homicide rates zooming in on a smaller unit of analysis. Lastly, this analysis aims to make an original contribution to the research base by exploring whether the length that the PAN party held a mayoral office impacted municipal homicide rates.</p>
</section>
<section id="iii.-data" class="level1">
<h1>III. Data</h1>
<p>The dataset utilized in this study comprises publicly available data from the National Institute of Statistics and Geography (INEGI), sourced from two GitHub repositories. The first repository aggregates homicide rate data spanning from 2000 to 2021, while the second repository provides election returns data compiled by Eric Magar, a professor of political science at Instituto Tecnológico Autónomo de México, covering the same period of time <span class="citation" data-cites="Magar_Recent_Mexican_Election_2018 mexico-homicide-rates">(<a href="#ref-Magar_Recent_Mexican_Election_2018" role="doc-biblioref">Magar 2018</a> ; <a href="#ref-mexico-homicide-rates" role="doc-biblioref">Gargiulo 2021</a>)</span>. Municipalities in Mexico serve as the unit of analysis for this research, encompassing the period from 2001 to 2020, with 2021 data omitted due to incomplete election cycles given that the next election is not being held until June 2024. Two independent variables are additive index variables I created from the original dataset. The first index variable is a Municipal Alternation Index, measuring the cumulative alternations in party power within municipalities over time. The second index variable is the PAN Power Index, quantifying the consecutive years of PAN governance at the municipal level. The third independent variable, Vote Margin, reflects the margin of victory for PAN candidates in mayoral elections. Elections where the margin of victory falls between -0.05 and 0.05 are considered close elections. The dependent variable in this analysis is the Post-election Homicide Rate, denoting the average homicide rate per 100,000 people in the period following a municipal election. It is calculated for each municipality and election cycle, capturing the level of violence observed in the aftermath of local elections.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Summary of Key Variables</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Municipal Alternation Index</td>
<td style="text-align: center; font-style: italic;">1.7156863</td>
<td style="text-align: center; font-style: italic;">0-7</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">PAN Power Index</td>
<td style="text-align: center; font-style: italic;">0.3461106</td>
<td style="text-align: center; font-style: italic;">0-7</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Margin of Victory (PAN Candidate)</td>
<td style="text-align: center; font-style: italic;">-0.0995015</td>
<td style="text-align: center; font-style: italic;">-0.469-0.458</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Post-election Homicide Rate</td>
<td style="text-align: center; font-style: italic;">14.1300071</td>
<td style="text-align: center; font-style: italic;">0-311.181</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="iv.-hypotheses" class="level1">
<h1>IV. Hypotheses</h1>
<p>I propose that municipalities experiencing close mayoral elections with a victory for the PAN (National Action Party) will exhibit higher post-election municipal homicide rates compared to municipalities where PAN candidates lost. I expect to observe this pattern from 2001 to 2020 because PAN-led crackdowns on drug trafficking organizations (DTOs) may intensify violence within a municipality. For instance, when law enforcement operations target DTOs, resulting in the arrest or elimination of high-ranking members, it creates vacancies in leadership roles. This vacuum can trigger internal power struggles among lower-ranking members vying for promotion, potentially escalating into violent conflicts as they compete for control within the organization. Furthermore, DTOs under police scrutiny become more vulnerable, attracting attacks from rival DTOs seeking to seize control of profitable drug trafficking routes. These rival DTOs may resort to violent tactics, including armed confrontations and territorial disputes, to exploit the weakened state of the incumbent DTO. Moreover, as criminal groups involved in the drug trade diversify their activities to evade enforcement, they may engage in other forms of criminal behavior such as extortion and human trafficking, specifically of undocumented immigrants as previously mentioned, contributing to increased overall homicide rates <span class="citation" data-cites="rosa2022mexican">(<a href="#ref-rosa2022mexican" role="doc-biblioref">Rosa Rodrı́guez 2022</a>)</span>. Therefore, it is plausible to expect that municipalities with PAN candidate victories, which may implement stricter anti-drug policies, could experience higher overall municipal homicide rates due to the ripple effects of anti-drug efforts on broader violence within communities. However, a caveat is that I only expect this relationship to be true when Mexico was under a PAN presidential administration. This is because the PAN party took a law and order stance on drug cartel activity, employing militarized crackdowns that directly antagonized DTOs. However, other parties like PRI and MORENA took less tough on crime approaches to cartel violence which means that at the municipal-level PAN mayors were operating separately from the federal agenda, limiting their power to enforce crackdowns and thus trigger violence at the local level.</p>
<p><em>Hypothesis 1 (H1): Municipalities with a PAN (National Action Party) candidate victory in local elections will experience a higher post-election municipal homicide rate per 100,000 people compared to municipalities where PAN candidates lost.</em></p>
<section id="extension-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="extension-hypotheses">Extension Hypotheses</h2>
<p>To extend my analysis, I look at the relationship between two governance variables: party rotation in mayoral office and the length of PAN mayoral governance.</p>
<p>I hypothesize that municipalities that experience a higher rotation of party leadership in the mayor’s office will exhibit higher post-election municipal homicide rates. This hypothesis is based on findings by Trejo and Ley that suggests that the rotation of political parties in the at the level of governer significantly contributed to the outbreak of intercartel violence and large-scale criminal wars in the early 2000s <span class="citation" data-cites="trejo2018did">(<a href="#ref-trejo2018did" role="doc-biblioref">Trejo and Ley 2018</a>)</span>. Furthermore, we can expect to see this relationship because each new mayoral administration brings in different priorities, policies, and approaches to addressing crime and a different relationship to DTO’s. This lack of consistency in governance may translate to instability and violence as the power structures of DTOs try to adapt to new governance strategies and politicians.</p>
<p><em>Hypothesis 2 (H2): Municipalities that experience a higher rotation of political parties in mayoral office will observe a higher post-election municipal homicide rate per 100,000 people compared to municipalities with stable party governance.</em></p>
<p>Additionally, I hypothesize that municipalities that experience longer stretches of having PAN mayor in office will exhibit lower post-election municipal homicide rates. This hypothesis is based on the premise that the stability provided by prolonged PAN governance may contribute to maintaining law and order, potentially reducing opportunities for violent conflicts to escalate. While H1 posits that PAN mayors trigger instability through crackdowns at first, this hypothesis expects that longevity in PAN governance would increase the effectiveness of PAN crackdowns in the long term.</p>
<p><em>Hypothesis 3 (H3): Municipalities with a higher index of PAN power stability, indicating longer periods of PAN party governance, will exhibit a lower municipal homicide rate per 100,000 people compared to municipalities with lower PAN power stability.</em></p>
</section>
</section>
<section id="v.-research-design" class="level1">
<h1>V. Research Design</h1>
<p>I employ a regression discontinuity (RD) approach to leverage the abrupt change in party affiliation at the threshold between PAN victories and losses to estimate the impact on violence for H1. This strategy capitalizes on close election outcomes to isolate idiosyncratic factors, ensuring robust analysis of the relationship between PAN victories and violence levels.</p>
<p>More specifically, in an RDD, treatment assignment is determined by a cutoff point, beyond which units receive treatment and below which they do not. This assignment variable, often referred to as the “running variable,” serves as an observable confounder, influencing both treatment assignment and the outcome. Importantly, treatment is solely determined by the assignment rule, ensuring that the assignment variable is not endogenous to competing interventions.</p>
<p>In the context of this study, the treatment assignment is determined by the electoral margin of victory for the mayoral PAN candidate. For instance, a PAN candidate winning an election by a small margin would be treated, while a loss by a similarly small margin would serve as the control. This setup ensures that treatment assignment is based solely on the electoral outcome and not influenced by other factors, guarding against confounding variables.</p>
<p>The RDD design allows me to estimate the local treatment effect (LATE), which captures the average effect of treatment for units in the vicinity of the cutoff point. Specifically, RDD identifies causal effects for subjects whose scores are close to the cutoff, effectively comparing individuals just above and below the threshold. In this study, the LATE translates to estimating the average effect of PAN victories in close elections on the post-election homicide rate for municipalities near the cutoff. Crucially, the RDD design relies on the continuity assumption, which posits that expected potential outcomes are continuous at the cutoff. This assumption ensures that any discontinuities observed in the outcome variable can be attributed to the treatment effect rather than competing interventions or confounding factors. In summary, the RDD design guards against confounders by leveraging the discontinuity in treatment assignment at the cutoff point, ensuring that treatment is determined solely by the running variable. By estimating the local treatment effect for units near the cutoff, RDD allows me to identify causal effects in this observational study while addressing selection bias.</p>
<p>The rdd model for hypothesis 1 can be expressed as:</p>
<p><span class="math display">\[
\text{Post-Election Homicide Rate}_i = \alpha + \tau D + \beta_1 (X - c) + \beta_2 D(X - c) + \text{Control Variables}_i + \epsilon
\]</span></p>
<p>Here, X represents the margin of victory for PAN mayoral candidates. C represents the treatment cutoff which is this study will be a vote margin of zero. D is a binary variable equal to 1 if X is greater than 0, indicating a PAN win.</p>
<p>The coefficient <span class="math inline">\(\tau\)</span> represents the effect of being treated, which is when a PAN mayor wins a close election, on the outcome variable of post-election homicide rate while accounting for the local linear relationship between the margin of victory, X, and the outcome. Therefore, <span class="math inline">\(\tau\)</span> captures the average effect of treatment for the units around the cutoff point or the local average treatment effect (LATE).</p>
<p>The coefficient <span class="math inline">\(\beta_1\)</span> captures the slope of the relationship between the margin of victory and the post-election homicide rate in the vicinity of the cutoff (zero) when D = 0, indicating a PAN loss. Essentially, it indicates the change in the outcome for a one-unit change in the margin of victory around the cutoff, holding D constant at 0.</p>
<p>The coefficient <span class="math inline">\(\beta_2\)</span> captures the discontinuity in the relationship between the margin of victory (X) and the outcome (Y) at the cutoff when D=1, indicating a PAN win. It measures the difference in the slope of the relationship between X and Y on either side of the cutoff due to the treatment effect. Essentially, it captures how the effect of the margin of victory on the outcome changes abruptly at the cutoff due to winning a close election.</p>
<section id="extension-hypotheses-regression-models" class="level2">
<h2 class="anchored" data-anchor-id="extension-hypotheses-regression-models">Extension Hypotheses Regression Models</h2>
<p>A significant challenge to hypothesizing a causal relationship between the PAN party winning the election and its effect on the post-election average homicide rate is the presence of unobserved confounders, variables that are not included in the analysis but are correlated with both the independent variable and the outcome. These unobserved confounders can bias the estimated causal effect if they are not properly accounted for.</p>
<p>Additionally, endogeneity threatens causal inference due to bidirectional relationships between the PAN party winning and increases in municipal homicide rates. In this case, the stability of the PAN party itself could be endogenous to homicide rates within municipalities. For example, if high homicide rates persist over time, voters may continue to support the PAN party due to its perceived stance on law and order. Moreover, political party stability can also affect policy decisions related to crime and violence. If the PAN party has a stable grip on power within a municipality, it may be better positioned to implement long-term policies and allocate resources towards crackdowns on drug cartels. However, if the party’s tenure in a municipality is uncertain, anti-cartel policy continuity may be disrupted, leading to inconsistencies in crime-fighting strategies, potentially influencing homicide rates.</p>
<p>Hypotheses 2 and 3 provide empirical extensions that can help to rule out potential confounders of Hypothesis 1 regarding the causal relationship between PAN party victories and post-election municipal homicide rates. H2 focuses on the rotation of political parties in mayoral office, drawing insights from Trejo and Ley, who found that such rotations contributed to increased inter-cartel violence before the Mexican War on Drugs. By examining the impact of party rotation on homicide rates, H2 aims to differentiate between stable and unstable party governance at the municipal level.</p>
<p>The regression model for Hypothesis 2 (H2) can be expressed as:</p>
<p><span class="math display">\[
\text{Post-election Homicide Rate}_i = \alpha + \beta_1{Party Alternation Index}_i + \text{Control Variables}_i + \epsilon
\]</span></p>
<p>In contrast, H3 tests the opposite direction of Trejo and Ley’s hypothesis by exploring the impact of PAN power stability, specifically examining longer periods of PAN governance, on homicide rates. H3 considers the potential stabilizing effect of prolonged PAN governance, which may lead to lower levels of violence due to the implementation of effective crime prevention strategies and establishment of stronger institutional frameworks. Therefore, while H2 focuses on the destabilizing effect of party alternation, H3 considers the potential stabilizing effect of prolonged PAN governance. Although they approach the concept of political stability from different angles, both hypotheses contribute to understanding how political party dynamics affect municipal homicide rates, offering complementary insights into the relationship between stability and violence and helping to mitigate potential confounding factors like political stability and instability.</p>
<p>The regression model for Hypothesis 3 (H3) can be expressed as:</p>
<p><span class="math display">\[
\text{Post-Election Homicide Rate}_i = \alpha + \beta_1{PAN Power Stability Index}_i + \text{Control Variables}_i + \epsilon
\]</span></p>
<p>For all models, I will be controlling for municipal population.</p>
</section>
</section>
<section id="vi.-findings" class="level1">
<h1>VI. Findings</h1>
<section id="graphical-analysis-of-violence-pattern" class="level2">
<h2 class="anchored" data-anchor-id="graphical-analysis-of-violence-pattern">Graphical Analysis of Violence Pattern</h2>
<p>Figure 1 examines post-election homicide rates against the PAN margin of victory across municipalities from 2001 to 2020, with a negative margin indicating a PAN loss. Each point represents average violence in 0.5 percentage point vote spread bins. The solid line plots predicted values from a regression of violence on the vote spread, estimated separately on either side of the PAN win-loss threshold. Across this large time frame, PAN victories had a substantive effect on the average post-election homicide rate, increasing the rate by approximately 2% following a close PAN victory, increasing from 14% to 16%, as compared to a close PAN loss. Figure 1 supports my hypothesis that municipalities with a PAN candidate victory in local elections will experience a higher post-election municipal homicide rate per 100,000 people compared to municipalities where PAN candidates lost.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Mexico-Elections-RDD-Paper_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Figure 1. This figure plots homicide rates against the PAN margin of victory for 2001-2020, with a negative margin indicating a PAN loss. Each point represents the average value of the outcome in vote spread bins of width one-half of a percent-age point. The solid line plots predicted values, with separate quadratic vote spread trends estimated on either side of the PAN win-loss threshold.</em></p>
<p>Figure 2 examines post-election homicide rates against the PAN margin of victory across municipalities and presidencies, with a negative margin indicating a PAN loss. Each point represents average violence in 0.5 percentage point vote spread bins aggregated by president in office. The solid line plots predicted values from a regression of violence on the vote spread, estimated separately on either side of the PAN win-loss threshold. Breaking the regression discontinuity down by president reveals interesting trends. Figure 2 shows that while a PAN candidate was president, either when Vicente Fox or Felipe Calderón was in office from 2000-2012, PAN victories at the municipal level had a positive effect on the average post-election homicide rate, increasing the rate by approximately 2% following a close PAN victory, as compared to a close PAN loss. This finding also supports my hypothesis showing that a PAN victory at the municipal level under a PAN president increased violence as a result of crackdown on drug cartels. Figure 2 also shows that under president Nieto, a PRI candidate, the post-election homicide rate increased by approximately 5% in municipalities with close PAN victories. Lastly, Figure 2 shows that under president Obrador, a MORENA candidate, the post-election homicide rate decreased by approximately 20% in municipalities with close PAN victories.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Mexico-Elections-RDD-Paper_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Figure 2. This figure plots homicide rates against the PAN margin of victory for 2001-2020 by president, with a negative margin indicating a PAN loss. Each point represents the average value of the outcome in vote spread bins of width one-half of a percent-age point. The solid line plots predicted values, with separate quadratic vote spread trends estimated on either side of the PAN win-loss threshold.</em></p>
</section>
<section id="regression-analysis" class="level2">
<h2 class="anchored" data-anchor-id="regression-analysis">Regression Analysis</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Bivariate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">PAN Win (with Control)</td>
<td style="text-align: center;">1.875(3.349)</td>
</tr>
<tr class="even">
<td style="text-align: center;">PAN Win (Fox 2000-2006, PAN)</td>
<td style="text-align: center;">2.897(3.762)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">PAN Win (Calderón 2006-2012, PAN)</td>
<td style="text-align: center;">0.914(5.643)</td>
</tr>
<tr class="even">
<td style="text-align: center;">PAN Win (Nieto 2012-2018, PRI)</td>
<td style="text-align: center;">6.514*(5.350)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">PAN Win (Obrador 2018-Present, MORENA)</td>
<td style="text-align: center;">-24.841(37.325)</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><em>Table 2. H1 Regression Table.</em></p>
<p>Table 2 presents estimates of the effect of PAN (National Action Party) winning close municipal elections on the post-election homicide rate per 100,000 people. The table shows the H1 model overall as well as the H1 model subsetted by president. In all models, the municipal population is controlled for. In Table 2, the overall Local Average Treatment effect (LATE), controlling for municipal population, is 1.875. This means that from 2001-2020 a PAN mayoral win causes an almost 2-point increase in the post-election homicide rate at the municipal level. Substantively, this a significant effect. For example, a municipality with a population of 643,447 people that experienced a 2% homicide rate increase would correspond to approximately 12.87 more homicides on average. However, this 2 point bump is not statistically significant (p &gt; 0.05).</p>
<p>The magnitude of the LATE changes when the model is run independently for each presidential administration. During the PAN Fox administration (2000-2006), the LATE increases to 2.897. During the PAN Calderón administration (2006-2012), the LATE decreases to 0.914. Given that the Calderón administration is the administration that officially began the war on drugs, the decrease in the LATE from the Fox to Calderón administration shows that under Calderón the effect of a PAN municipal win caused a smaller increase in the post-election homicide rate than under Fox. However, these coefficients are statistically insignificant. During the PRI party Nieto administration (2012-2018), the LATE increases to 6.514. This is the only coefficient in Table 2 that reaches conventional levels of statistical significance (p &gt; 0.05). Interpreted in a real-world context, this coefficient means that the effect of a PAN municipal win caused a larger increase in the post-election homicide rate than under a PRI president. This shows that when the presidential administration and local government are unaligned, given that PAN and PRI are opposing parties, PAN mayors may be less effective at imposing a crackdown on criminal violence at the municipal level. Under the MORENA party Obrador (2018-Present), the LATE for PAN wins drastically decreases to -24.841. This coefficient is an extremely large, but not statistically significant, and should be interpreted with caution. The decrease in the LATE under President Andrés Manuel López Obrador’s administration could be attributed to President Obrador’s shift towards civilian-led policing however more research would be needed. The lack of statistical significance for most coefficients, including the large effect under Obrador, could be influenced by sample size. Notably, the sample size for the Obrador administration is very small, 375 observations, which may reduce the statistical power of the hypothesis test. A smaller sample size can lead to wider confidence intervals and decreased sensitivity to detect true effects, making it more challenging to achieve statistical significance.</p>
<div class="cell">
<div class="cell-output-display">
 

  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tinytable_71whp6oh0t7y8xg3bvpz</title>
    <style>
.table td.tinytable_css_pg7fk46r07x5obye031s, .table th.tinytable_css_pg7fk46r07x5obye031s {    border-bottom: solid 0.1em #d3d8dc; }
.table td.tinytable_css_nbb0ua5p1c7gr40gobkm, .table th.tinytable_css_nbb0ua5p1c7gr40gobkm {    text-align: left; }
.table td.tinytable_css_twfxc2287o4kt2gh3mlx, .table th.tinytable_css_twfxc2287o4kt2gh3mlx {    text-align: center; }
.table td.tinytable_css_89jdph8zwhiemyovuqlg, .table th.tinytable_css_89jdph8zwhiemyovuqlg {    border-bottom: solid 0.05em black; }
    </style>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <script>
    MathJax = {
      tex: {
        inlineMath: [['$', '$'], ['\\(', '\\)']]
      },
      svg: {
        fontCache: 'global'
      }
    };
    </script>
  

  
    <div class="container">
      <table class="table table-borderless" id="tinytable_71whp6oh0t7y8xg3bvpz" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <thead>
        
              <tr>
                <th scope="col"> </th>
                <th scope="col">Bivariate</th>
              </tr>
        </thead>
        
        <tbody>
                <tr>
                  <td>(Intercept)            </td>
                  <td>12.934*** (0.274)</td>
                </tr>
                <tr>
                  <td>Party Alternation Index</td>
                  <td>0.668*** (0.119) </td>
                </tr>
                <tr>
                  <td>Municipal Population   </td>
                  <td>0.000 (0.000)    </td>
                </tr>
                <tr>
                  <td>Num.Obs.               </td>
                  <td>12364            </td>
                </tr>
                <tr>
                  <td>R2 Adj.                </td>
                  <td>0.002            </td>
                </tr>
        </tbody>
      </table>
    </div>

    <script>
      function styleCell_tinytable_nt2pfz8cmhkw33dz40em(i, j, css_id) {
        var table = document.getElementById("tinytable_71whp6oh0t7y8xg3bvpz");
        table.rows[i].cells[j].classList.add(css_id);
      }
      function insertSpanRow(i, colspan, content) {
        var table = document.getElementById('tinytable_71whp6oh0t7y8xg3bvpz');
        var newRow = table.insertRow(i);
        var newCell = newRow.insertCell(0);
        newCell.setAttribute("colspan", colspan);
        // newCell.innerText = content;
        // this may be unsafe, but innerText does not interpret <br>
        newCell.innerHTML = content;
      }
      function spanCell_tinytable_nt2pfz8cmhkw33dz40em(i, j, rowspan, colspan) {
        var table = document.getElementById("tinytable_71whp6oh0t7y8xg3bvpz");
        const targetRow = table.rows[i];
        const targetCell = targetRow.cells[j];
        for (let r = 0; r < rowspan; r++) {
          // Only start deleting cells to the right for the first row (r == 0)
          if (r === 0) {
            // Delete cells to the right of the target cell in the first row
            for (let c = colspan - 1; c > 0; c--) {
              if (table.rows[i + r].cells[j + c]) {
                table.rows[i + r].deleteCell(j + c);
              }
            }
          }
          // For rows below the first, delete starting from the target column
          if (r > 0) {
            for (let c = colspan - 1; c >= 0; c--) {
              if (table.rows[i + r] && table.rows[i + r].cells[j]) {
                table.rows[i + r].deleteCell(j);
              }
            }
          }
        }
        // Set rowspan and colspan of the target cell
        targetCell.rowSpan = rowspan;
        targetCell.colSpan = colspan;
      }

window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(0, 0, 'tinytable_css_pg7fk46r07x5obye031s') })
window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(0, 1, 'tinytable_css_pg7fk46r07x5obye031s') })
window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(0, 0, 'tinytable_css_nbb0ua5p1c7gr40gobkm') })
window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(1, 0, 'tinytable_css_nbb0ua5p1c7gr40gobkm') })
window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(2, 0, 'tinytable_css_nbb0ua5p1c7gr40gobkm') })
window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(3, 0, 'tinytable_css_nbb0ua5p1c7gr40gobkm') })
window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(4, 0, 'tinytable_css_nbb0ua5p1c7gr40gobkm') })
window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(5, 0, 'tinytable_css_nbb0ua5p1c7gr40gobkm') })
window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(0, 1, 'tinytable_css_twfxc2287o4kt2gh3mlx') })
window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(1, 1, 'tinytable_css_twfxc2287o4kt2gh3mlx') })
window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(2, 1, 'tinytable_css_twfxc2287o4kt2gh3mlx') })
window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(3, 1, 'tinytable_css_twfxc2287o4kt2gh3mlx') })
window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(4, 1, 'tinytable_css_twfxc2287o4kt2gh3mlx') })
window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(5, 1, 'tinytable_css_twfxc2287o4kt2gh3mlx') })
window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(3, 0, 'tinytable_css_89jdph8zwhiemyovuqlg') })
window.addEventListener('load', function () { styleCell_tinytable_nt2pfz8cmhkw33dz40em(3, 1, 'tinytable_css_89jdph8zwhiemyovuqlg') })
    </script>

  


</div>
</div>
<p><em>Table 3. H2 Regression Table.</em></p>
<p>Table 3 shows that for each unit increase in the Municipal Alternation Index, which indicates an increase in the cumulative amount of alternations in party power within municipalities over time, there is an increase of 0.668 in the post-election average homicide rate, holding municipal population constant. Substantively, the effect size is a significant magnitude, indicating that party alteration is associated with noticeable changes in the post-election homicide rate. The coefficient for the alternation_index variable is also statistically significant at conventional levels (p &lt; 0.001) indicating that the observed relationship between alternation index and post-election homicide rate is unlikely to have occurred by chance.</p>
<div class="cell">
<div class="cell-output-display">
 

  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tinytable_s7t5b8kzm58x8m3zmmln</title>
    <style>
.table td.tinytable_css_41arhe499nall0vjqcoz, .table th.tinytable_css_41arhe499nall0vjqcoz {    border-bottom: solid 0.1em #d3d8dc; }
.table td.tinytable_css_txq567nfaimvgflnfzgm, .table th.tinytable_css_txq567nfaimvgflnfzgm {    text-align: left; }
.table td.tinytable_css_vrclamxtxydixuzcdqnf, .table th.tinytable_css_vrclamxtxydixuzcdqnf {    text-align: center; }
.table td.tinytable_css_xpwxmkq916vy7oavjvuz, .table th.tinytable_css_xpwxmkq916vy7oavjvuz {    border-bottom: solid 0.05em black; }
    </style>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <script>
    MathJax = {
      tex: {
        inlineMath: [['$', '$'], ['\\(', '\\)']]
      },
      svg: {
        fontCache: 'global'
      }
    };
    </script>
  

  
    <div class="container">
      <table class="table table-borderless" id="tinytable_s7t5b8kzm58x8m3zmmln" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <thead>
        
              <tr>
                <th scope="col"> </th>
                <th scope="col">Bivariate</th>
              </tr>
        </thead>
        
        <tbody>
                <tr>
                  <td>(Intercept)         </td>
                  <td>14.084*** (0.196)</td>
                </tr>
                <tr>
                  <td>PAN Power Index     </td>
                  <td>0.009 (0.220)    </td>
                </tr>
                <tr>
                  <td>Municipal Population</td>
                  <td>0.000 (0.000)    </td>
                </tr>
                <tr>
                  <td>Num.Obs.            </td>
                  <td>12364            </td>
                </tr>
                <tr>
                  <td>R2 Adj.             </td>
                  <td>0.000            </td>
                </tr>
        </tbody>
      </table>
    </div>

    <script>
      function styleCell_tinytable_czkrld2iscfbhag0w8lg(i, j, css_id) {
        var table = document.getElementById("tinytable_s7t5b8kzm58x8m3zmmln");
        table.rows[i].cells[j].classList.add(css_id);
      }
      function insertSpanRow(i, colspan, content) {
        var table = document.getElementById('tinytable_s7t5b8kzm58x8m3zmmln');
        var newRow = table.insertRow(i);
        var newCell = newRow.insertCell(0);
        newCell.setAttribute("colspan", colspan);
        // newCell.innerText = content;
        // this may be unsafe, but innerText does not interpret <br>
        newCell.innerHTML = content;
      }
      function spanCell_tinytable_czkrld2iscfbhag0w8lg(i, j, rowspan, colspan) {
        var table = document.getElementById("tinytable_s7t5b8kzm58x8m3zmmln");
        const targetRow = table.rows[i];
        const targetCell = targetRow.cells[j];
        for (let r = 0; r < rowspan; r++) {
          // Only start deleting cells to the right for the first row (r == 0)
          if (r === 0) {
            // Delete cells to the right of the target cell in the first row
            for (let c = colspan - 1; c > 0; c--) {
              if (table.rows[i + r].cells[j + c]) {
                table.rows[i + r].deleteCell(j + c);
              }
            }
          }
          // For rows below the first, delete starting from the target column
          if (r > 0) {
            for (let c = colspan - 1; c >= 0; c--) {
              if (table.rows[i + r] && table.rows[i + r].cells[j]) {
                table.rows[i + r].deleteCell(j);
              }
            }
          }
        }
        // Set rowspan and colspan of the target cell
        targetCell.rowSpan = rowspan;
        targetCell.colSpan = colspan;
      }

window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(0, 0, 'tinytable_css_41arhe499nall0vjqcoz') })
window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(0, 1, 'tinytable_css_41arhe499nall0vjqcoz') })
window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(0, 0, 'tinytable_css_txq567nfaimvgflnfzgm') })
window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(1, 0, 'tinytable_css_txq567nfaimvgflnfzgm') })
window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(2, 0, 'tinytable_css_txq567nfaimvgflnfzgm') })
window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(3, 0, 'tinytable_css_txq567nfaimvgflnfzgm') })
window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(4, 0, 'tinytable_css_txq567nfaimvgflnfzgm') })
window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(5, 0, 'tinytable_css_txq567nfaimvgflnfzgm') })
window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(0, 1, 'tinytable_css_vrclamxtxydixuzcdqnf') })
window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(1, 1, 'tinytable_css_vrclamxtxydixuzcdqnf') })
window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(2, 1, 'tinytable_css_vrclamxtxydixuzcdqnf') })
window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(3, 1, 'tinytable_css_vrclamxtxydixuzcdqnf') })
window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(4, 1, 'tinytable_css_vrclamxtxydixuzcdqnf') })
window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(5, 1, 'tinytable_css_vrclamxtxydixuzcdqnf') })
window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(3, 0, 'tinytable_css_xpwxmkq916vy7oavjvuz') })
window.addEventListener('load', function () { styleCell_tinytable_czkrld2iscfbhag0w8lg(3, 1, 'tinytable_css_xpwxmkq916vy7oavjvuz') })
    </script>

  


</div>
</div>
<p><em>Table 4. H2 Regression Table.</em></p>
<p>Table 4 shows that for each unit increase in the PAN Power Index, which indicates an increase in the consecutive years of PAN governance at the municipal level, there is an increase of 0.009 in the post-election average homicide rate, holding municipal population constant. Substantively, the effect size is somewhat small, indicating that PAN power stability is somewhat associated with a small increase in the post-election homicide rate. The coefficient for the PAN Power Index variable is also not statistically significant at conventional levels.</p>
</section>
</section>
<section id="vii.-discussion-and-policy-implications" class="level1">
<h1>VII. Discussion and Policy Implications</h1>
<p>Overall, there is evidence in support of H1 that municipalities with a PAN candidate victory will experience higher post-election homicide rates. However, this was only true when a PAN or PRI candidate was in presidential office. That is, when a hyper-aligned or unaligned candidate was president. When the third party, MORENA, was in power, municipalities with a PAN candidate victory experienced much lower post-election homicide rates. This may suggest that polarized stances on drug cartels influences municipal homicide rates. However, we must interpret these findings with caution given that the only statistically significant effect was found for the model run for elections that occurred during the Nieto administration. There is also evidence in support of H2, that municipalities with higher party rotation in mayoral office will have higher post-election homicide rates, and H3, that municipalities with longer periods of PAN mayoral governance will exhibit lower post-election homicide rates. However, it seems party rotation has a bigger positive effect on post-election homicide rates than PAN party stability. In sum, my findings indicate that PAN governance, increased party alteration, and increased PAN party rule at the municipal level is correlated with a increase in post-election homicide rates.</p>
<p>In terms of methodology, my findings suggest that RDD may not be an appropriate research design to measure the variation in the effect of PAN municipal governance on post-election homicide rates across presidential administrations given the lack of statistical significance in my findings. In particular, the RDD model is sensitive when it comes to small sample sizes as seen with the large negative Obrador coefficient. Thus, although my hypothesis is valid under the context of PAN presidents, we will need to reconsider how to measure the effect of PAN governance at the municipal level on homicide rates when it is threatened by the confounder of presidential oversight.</p>
<p>While the results provide valuable insights into the complex relationship between political dynamics and crime rates in Mexico in the context of the War on Drugs, they are not conclusive. The lack of statistical significance in some cases and the variations across presidential administrations highlight the need for further research. Future studies could delve deeper into how federal-local party alignment may influence the implementation of drug-crime policy and effect crime rates. Additionally, my empirical extension did not rule out the confounders of party stability and PAN time in power. Instead, the H2 and H3 models confirmed that frequent changes in what party is in power at the municipal level and the increased tenure of PAN mayors both increase post-election municipal homicide rates.</p>
<p>From a policy perspective, this project provides evidence that PAN municipal governance under PAN presidents has been largely ineffective at decreasing violence with tough-on-crime stances leading to an increase in post-election homicide rates. Additionally, when examining crime policy at the municipal level, Mexican policymakers should consider the impact of political party stability on their work. If policies are likely to not survive into the next administration, increasing instability in the local government-cartel relationship, the policies may be more likely to increase municipal violence. Crime approaches which help maintain stability in the government’s treatment of cartels and avoid shifting cartel power dynamics may be less likely to promote the onset of high rates of homicidal violence.</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-dell2015trafficking" class="csl-entry" role="listitem">
Dell, Melissa. 2015. <span>“Trafficking Networks and the Mexican Drug War.”</span> <em>American Economic Review</em> 105 (6): 1738–79.
</div>
<div id="ref-espinosa2015did" class="csl-entry" role="listitem">
Espinosa, Valeria, and Donald B Rubin. 2015. <span>“Did the Military Interventions in the Mexican Drug War Increase Violence?”</span> <em>The American Statistician</em> 69 (1): 17–27.
</div>
<div id="ref-cfr2024" class="csl-entry" role="listitem">
Foreign Relations, Council on. 2024. <span>“Global Conflict Tracker: Criminal Violence in Mexico.”</span> <a href="https://www.cfr.org/global-conflict-tracker/conflict/criminal-violence-mexico" class="uri">https://www.cfr.org/global-conflict-tracker/conflict/criminal-violence-mexico</a>.
</div>
<div id="ref-mexico-homicide-rates" class="csl-entry" role="listitem">
Gargiulo, Maria. 2021. <span>“<span class="nocase">Monthly municipal-level crude homicide rates in Mexico from January 2000 to December 2022</span>.”</span> <a href="https://github.com/thegargiulian/mexico-homicide-rates">https://github.com/thegargiulian/mexico-homicide-rates</a>.
</div>
<div id="ref-Magar_Recent_Mexican_Election_2018" class="csl-entry" role="listitem">
Magar, Eric. 2018. <span>“<span>Recent Mexican Election Vote Returns</span>.”</span> <a href="https://github.com/emagar/elecRetrns">https://github.com/emagar/elecRetrns</a>.
</div>
<div id="ref-rosa2022mexican" class="csl-entry" role="listitem">
Rosa Rodrı́guez, Paola Iliana de la. 2022. <span>“The Mexican War Against Drug Cartels, Traffickers’ Collateral Incentive to Commit Crimes Against Undocumented Immigrants.”</span> <em>Estudios Fronterizos</em> 23.
</div>
<div id="ref-trejo2018did" class="csl-entry" role="listitem">
Trejo, Guillermo, and Sandra Ley. 2018. <span>“Why Did Drug Cartels Go to War in Mexico? Subnational Party Alternation, the Breakdown of Criminal Protection, and the Onset of Large-Scale Violence.”</span> <em>Comparative Political Studies</em> 51 (7): 900–937.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>